spring.application.name=ProductAndOrderAPI
# 2. Cấu hình kết nối MySQL (Thay đổi password theo máy bạn)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Cấu hình JPA (Hibernate) - Đây là phần "Ma thuật"
# update: Tự động tạo/cập nhật bảng trong DB dựa trên code Java (bạn không cần viết CREATE TABLE)
spring.jpa.hibernate.ddl-auto=update
# MySQLDialect: Giúp Hibernate hiểu ngữ pháp MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 4. Log SQL (Để bạn thấy câu lệnh SQL chạy ngầm - Rất tốt khi debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 5. JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000